### PR TITLE
committing GenerateTable.py and its documentation

### PR DESCRIPTION
**Pull request by CemIskir**
Table creation from JSON file

Final changes are submitted.

Crafted the code to create tables, intermediate tables(for many to many relations), and system tables(tables a user have) from given username, JSON file, and .db file
Also developed the function getAllTableNames which returns all of the tables belonging to the same user

### CODE REVIEW

**Comment by fabianmuehlboeck** [comment]
This is missing tests

**Comment by CemIskir** [comment]
I have example.json file where I pass it to the function by calling processJSON('anyUser','example.db','example.json') at the end of the file. Do you want a separate file?

**Comment by fabianmuehlboeck** [comment]
I meant unit-tests for python code.

**Comment by CemIskir** [comment]
Working on it, I will submit in 1 hour

**Pull request merged**
